# -*- coding: utf-8 -*-
"""ml_linear_regression1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RmyIMVfbryfom8iHoKL5ia-5XR4EpO5r

# This program makes a plot.
#
# Plot with data:
#  + diameter of pizza (X, horizontal axis)
#  + price in dollars (Y, vertical axis)
#
"""

# Use Matplotlib
import matplotlib.pyplot as plt

# diameter of pizza (inches)
X = [[4], [8], [12], [16], [18]]
# price ($)
y = [[4], [8], [10], [12], [15]]

# Create plot with matplotlib
plt.figure()
plt.title('Pizza price vs diameter')
plt.xlabel('Diameter in inches')
plt.ylabel('Price in dollars')
plt.plot(X, y, 'k.', color='red')
plt.axis([0, 25, 0, 25])
plt.grid(True)
plt.show()