# -*- coding: utf-8 -*-
"""ML_Iris_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQqgQN7PHC7RipCGrF_FC0fjHMEMqbcB

# Example of Classification Algorithm
# Real World Data: "Iris Flower Dataset"

# Data =
#  Classes: "Setosa" (0), "Versicolour" (1) and "Virginica" (2)
#  Features: "Petal length", "Petal width", "Sepal length", "Sepal width"

# Task = "Predict Flower [0,1 or 2], Given 4 new features".
"""

# Load Classification Algorithm
from sklearn import tree

#Import Example Dataset "Iris Flowers"
from sklearn.datasets import load_iris

# Load Example Dataset "Iris Flowers"
iris = load_iris()
#print the feature names of Iris
print(iris.feature_names)
#print the target names of Iris
print(iris.target_names)

print(iris.data[0])