# -*- coding: utf-8 -*-
"""ML_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NHknk39IgxdZa2cb78azKolhA0Zt9y04
"""

# Load Algorithm
from sklearn import tree

"""**Cat or Fish Classification**"""

### Step 1: Create Training Data (= features and labels)

# Labels are class outcomes (0 or 1) (0 for fish, 1 for cat)
labels = [0,0,0,1,0]
# Features are measurements (legs, weight)
features = [[0,50],[0,150000],[4,5],[4,6],[0,0.05]]

### Step 2: Initialize and Train algorithm

# Initialize Classification Algorithm named DecisionTree
algorithm = tree.DecisionTreeClassifier()

# Train algorithm with training data (features,labels)
algorithm = algorithm.fit(features, labels)

### Step 3: Predict

# New data/measurements: [4 legs, 6kg]
#newData = [[0,30]] #[0]
newData = [[4,6]] #[1]
# Predict fish (0) or cat (1)?
print(algorithm.predict(newData))

"""**Key facts**

Machine Learning Algorithms learn from experience (training data)

A classifier is a type of Machine Learning Algorithm

A classifier algorithm can predict a class/category, given new data as input

If the training set contains labeled outputs and inputs, its called a supervised learning algorithm
"""