# -*- coding: utf-8 -*-
"""vehicle_classification_exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x2-lkOTge1Ixyil88sKMyHSIeCA3BEnW
"""

# Load Algorithm
from sklearn import tree

"""#Create your own classifier. Given new data, predict if its a car (1) or motorcycle (0)."""

## Step 1: Create Training Data (= features and labels)

# Labels are class outcomes (0 or 1) (0 for car, 1 for motorcycle)
labels = [0,0,1,0,1,1,0,0]

# Features are measurements (wheels, seats)
features = [[2,2],[2,2],[3,4],[2,2],[4,4],[4,4],[3,2],[2,2]]

### Step 2: Initialize and Train algorithm

# Initialize Classification Algorithm named DecisionTree
algorithm = tree.DecisionTreeClassifier()

# Train algorithm with training data (features,labels)
algorithm = algorithm.fit(features, labels)

### Step 3: Predict

# New data/measurements: [3 wheels, 4 seats]
newData = [[3,4]] #[1]
# Predict car (1) or motocycle (0)?
print(algorithm.predict(newData))

# New data/measurements: [2 wheels, 2 seats]
newData2 =[[2,2]] #[0]
print(algorithm.predict(newData2))